# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df954158e53472de001c9259dfbf0f1566399dc7227661dc2825bbb1ae02c476c982190f90a756b9f986de329c97f3f25d2ceef5433e125d0885c77a22aa9145

test:
  secret_key_base: 1f9f268ae397e6b67aee76551228134b5225cc6a2df7dda16d83c6af11d5efd8d7f7f5ad78cc682e88b952f5e2522a588d282151a4c9e0ddd3cbbd7fc4fdfc37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
